name: components_sample
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  cupertino_icons: ^1.0.6
  gap:


dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint:
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
